language: c++
sudo: required
services:
- docker
cache:
  directories:
  - build
script:
- export CARGO_HOME=$HOME/.cargo
- docker pull michaelfbryan/ffi-guide
- docker run -v $(pwd):/code 
    -v $CARGO_HOME:$CARGO_HOME \
    -e CARGO_HOME \
    michaelfbryan/ffi-guide ci/test.sh
after_success:
  - docker run -v $(pwd):/code \
    -v $CARGO_HOME:$CARGO_HOME \
    -e AWS_SECRET_ACCESS_KEY \
    -e AWS_ACCESS_KEY_ID \
    -e CARGO_HOME_DIR \
    michaelfbryan/ffi-guide ci/deploy.sh
env:
  global:
  - secure: a2K6Q+A+kiGkXhuz9FjHfANvCtCRkDLgW7Z44HJPvoyDCCb3CBiMiIOnXzdB9T8N/TsU9bAttWywZ+3WMId/xil8lXI7t2cObns+ecfgNhJ+GWFzG3NYJSEAYYt98sgj07r7FDLP5LeknsYjFUy+FVVVhaKOH4izvITw+uNsb9oDvoNkIb1uSghkhn9igDxfLjSQij6aqQXOoPjpUgMwmP0pkWZtXmFXULHrvFVgTOzJ75W2WnqdkO6dk6g4R7H0VZDASAScOIFlUFdRABPNckSirv6d372gxUWZ40teG7PadFnwQlkIqCUUAdvfPy7c4zxf3KhtjLfnWNhuIZcBytzpz0tsqpVUT04CPUvQXhXGN1lU+RPHdvKJS54G6eoTJ9R1s3RdIL2u3hVvVQEDOzvFGEzr+awFkwh+jtO9Xr5aib2aj5Ii2qT1Pw1Xo5M8Ftpg+OKBYL+sHU8upe+oIYduMWZ2iPDjcAPHz12wf11zITgvi1voQSNtzYJNmCVVSGsM0UiYx4a/+P7fTZCaEhk5oPsSqjETiOTKirTFxjA+CS4/6GZo42ErKveMIfVTP/xjRSsVmSkuS49U0ULYT/VEssEj7vjzlA1hRQ3P2NP4zfZIyay8P8XBh2ms/JItFxmEa0xcw8LvbKIPuYgE+xkHxLLfRpeDxlYt2YE6tJs=
  - secure: lVAwpzQHYCcp3v7Mni+ZadpCMx5EGOwAmzmRN5zhsHM91rSu/GtxcmqpLC4J+vY4CE4kHgxMdZuxsp9u9+M3N2V2JDDSZxFFDBQcIpwQOVaMG9cV2kzYkOy6Yamg83xh7ntvpAsS3by1ZwICBxKU+Bi+XXxuWDdl3akFvgDjlzF989PdAHIC0hylkaB9gwigWSH4IQcxU/nNa4b66iSxhITvK+JUwu9qFLNIodqjwt91VnE6DH0mWWxpwToCJ/FLIr6up7uCrgoZ1IkU/u0Zts/fdpeHkHcCJA6hQRyNVjBRN3/tSSKRP5WinMSn45d51IGAXChyaYG4N8PJ848MH98o/L1gGy/vnDN4t05ucdt0El+ZlLrne6qG/4ISh8nQ6gXskpqGyzx+CIDi4bC0lgKTLbjoQOOKr/HOQt/PZW7SsQX1uPtPvhzOmo/tyeVmsJ/haWuGC9KnhNcMKj6QcH1eeGfAuBGtCHnY4kNIuhye1kyIvpC5s1uv7NacSJ9UojHp525S/2L/V0SDWbpi8Mj7HUvwksOHd1Ob9uRM7eXJDHLRagCNOVHx0A3Ybsk+LKqAiLZEKzY2Wq0CehtYJb9+t19Afv8RYG92P5WtagIgyvZm77n/plH9T1NkXEb/1jTMvLUQHqSL0ZyPe8uhg7Kibfax7/F33gh+ro2jizU=
  - secure: BX6CriRi21hwgSz3j3oTCwAJ9YOaAFEP+rj7tZygumdH5TqzsVEbr8Dwc7MsjOVU00lIIMfXWUadl59kwXtAGYjzLOKbc/dBNoWK0QqVmmV0uAMBHUtBYxoeniy45xFlGinsAd3bY0xTfxIEJCn4b+tNUOuHS0x7f1PZPAcZklBtmm+0ytfFVBIZ1PUFUSD0B7UAVpXAtzfxYyKGxB/PrTKV/KfhdZWhLQ/Z4HSP5zARvxU3Jj1uiaaVc+aUx9l2DwVGocNJqqGEdS86zlvnMXWGLd63VQXs/Oaj2pbVB/IU2zaICcZo12Zgdg6FS7jQONsuVMndp13Caz+rSg5lUn42MhaLphfLjv+aDd+QdVNDA9MBzBTUDs+oJ8GLGX2M5ATQV757TiNfdqa7/qBAEzIfjdZjRjdb9Fr1RdB9jMk3aOGRp9TGX7CB9Uc1tIIxnD7cm7F+oMRvzEdrcKhiVTg+vGRDFwyp2SPR1yvu5zOQyftB7i/GxxFSdVCchUM/+MbzCKjqSKxZ692FXQXvHAle4ce7JmPOdR8HYViphc1XqVEv/ZQKJHbtide8LzRl2M7RkhMC5U/auaLFs2ErsX7Faey305wjOH+aJWMxrPQy6lwurddHUTstTDOGJLnhwEISojHNm/MbJx0qAYNMuyBRlv5FXdxRtPNPOhEsrY4=
